// ============================================================
// Mir2 现代客户端 — Delphi 旧版协议到新版协议的映射表
// 职责：记录经典 Delphi 客户端消息与新版 client_v1 协议
//       之间的对应关系、迁移状态和遗留说明
//
// 背景：
// 经典传奇（Mir2）的 Delphi 客户端使用一种基于文本行的
// 协议格式（每条消息以文本行的形式发送，如 'LOGIN' 等）。
// 本新版客户端改用结构化的二进制协议（client_v1），
// 此映射表记录了旧版 Delphi 消息到新版 C++ 消息之间的
// 对应关系，用于指导协议迁移和验证实现的完整性。
//
// 映射表中的每个条目独立记录一条消息的迁移状态：
// - implemented: 已在新版中完整实现
// - partial: 部分实现（核心功能可用，边缘情况未处理）
// - planned: 已列入计划，但尚未实现
// - internal: 内部机制变化（非直接消息映射）
// ============================================================
#pragma once

#include <array>
#include <cstdint>
#include <string_view>

namespace mir2::client::protocol_migration {

/// 迁移状态枚举
enum class MigrationStatus {
  implemented,  ///< 已在新版协议中完整实现
  partial,      ///< 部分实现（基本功能可用，细节待完善）
  planned,      ///< 已计划，尚未实现
  internal      ///< 内部机制变更，非直接消息映射
};

/// 映射条目结构
struct MappingEntry {
  std::string_view delphi_entry;  ///< 旧版 Delphi 函数/消息名（如在 ClFunc.pas 中的声明）
  std::string_view cxx_entry;     ///< 新版 C++ 函数/结构体名
  std::string_view domain;        ///< 所属功能域（如 login/character/inventory/magic）
  MigrationStatus status;         ///< 迁移状态
  std::string_view notes;         ///< 备注说明（迁移差异/注意事项）
};

enum class LegacyProtocolDirection {
  client_to_server,
  server_to_client
};

enum class LegacyProtocolMappingStatus {
  implemented,
  partial,
  planned,
  internal,
  legacy_only,
  not_migrated
};

struct LegacyMessageMappingEntry {
  std::string_view delphi_symbol;
  std::uint16_t delphi_ident;
  LegacyProtocolDirection direction;
  std::string_view delphi_source;
  std::string_view cxx_legacy_symbol;
  std::string_view client_v1_entry;
  LegacyProtocolMappingStatus status;
  std::string_view notes;
};

/// 迁移状态转字符串
inline constexpr std::string_view to_string(const MigrationStatus status) {
  switch (status) {
    case MigrationStatus::implemented: return "implemented";
    case MigrationStatus::partial:     return "partial";
    case MigrationStatus::planned:     return "planned";
    case MigrationStatus::internal:    return "internal";
  }
  return "unknown";
}

inline constexpr std::string_view to_string(const LegacyProtocolMappingStatus status) {
  switch (status) {
    case LegacyProtocolMappingStatus::implemented: return "implemented";
    case LegacyProtocolMappingStatus::partial:     return "partial";
    case LegacyProtocolMappingStatus::planned:     return "planned";
    case LegacyProtocolMappingStatus::internal:    return "internal";
    case LegacyProtocolMappingStatus::legacy_only: return "legacy_only";
    case LegacyProtocolMappingStatus::not_migrated: return "not_migrated";
  }
  return "unknown";
}

inline constexpr std::string_view to_string(const LegacyProtocolDirection direction) {
  switch (direction) {
    case LegacyProtocolDirection::client_to_server: return "client_to_server";
    case LegacyProtocolDirection::server_to_client: return "server_to_client";
  }
  return "unknown";
}

namespace detail {

inline constexpr std::string_view kGrobal2Source = "Source/Common/Grobal2.pas";

inline constexpr LegacyMessageMappingEntry cm(std::string_view delphi_symbol,
                                              std::uint16_t delphi_ident,
                                              std::string_view cxx_legacy_symbol,
                                              std::string_view client_v1_entry,
                                              LegacyProtocolMappingStatus status,
                                              std::string_view notes) {
  return LegacyMessageMappingEntry{delphi_symbol,
                                   delphi_ident,
                                   LegacyProtocolDirection::client_to_server,
                                   kGrobal2Source,
                                   cxx_legacy_symbol,
                                   client_v1_entry,
                                   status,
                                   notes};
}

inline constexpr LegacyMessageMappingEntry sm(std::string_view delphi_symbol,
                                              std::uint16_t delphi_ident,
                                              std::string_view cxx_legacy_symbol,
                                              std::string_view client_v1_entry,
                                              LegacyProtocolMappingStatus status,
                                              std::string_view notes) {
  return LegacyMessageMappingEntry{delphi_symbol,
                                   delphi_ident,
                                   LegacyProtocolDirection::server_to_client,
                                   kGrobal2Source,
                                   cxx_legacy_symbol,
                                   client_v1_entry,
                                   status,
                                   notes};
}

}  // namespace detail

// ====================================================================
// Delphi protocol constant audit tables.
//
// These tables account for every CM_* and SM_* value declared in
// Source/Common/Grobal2.pas. They are audit metadata only: adding an entry
// here does not implement new gameplay protocol behavior.
// ====================================================================
inline constexpr std::array<LegacyMessageMappingEntry, 87>
    kDelphiClientToServerMessageMappings{{
        detail::cm("CM_PROTOCOL", 2000, "", "ClientHello",
                   LegacyProtocolMappingStatus::internal,
                   "Legacy protocol probe; client_v1 uses ClientHello."),
        detail::cm("CM_IDPASSWORD", 2001, "kCmIdPassword", "LoginRequest",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::cm("CM_ADDNEWUSER", 2002, "kCmAddNewUser", "CreateAccountRequest",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::cm("CM_CHANGEPASSWORD", 2003, "kCmChangePassword", "ChangePasswordRequest",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::cm("CM_UPDATEUSER", 2004, "kCmUpdateUser", "UpdateAccountRequest",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::cm("CM_QUERYCHR", 100, "kCmQueryChr", "CharacterListRequest",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::cm("CM_NEWCHR", 101, "kCmNewChr", "CreateCharacterRequest",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::cm("CM_DELCHR", 102, "kCmDelChr", "DeleteCharacterRequest",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::cm("CM_SELCHR", 103, "kCmSelChr", "SelectCharacterRequest",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::cm("CM_SELECTSERVER", 104, "kCmSelectServer", "SelectServerRequest",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::cm("CM_THROW", 3005, "", "",
                   LegacyProtocolMappingStatus::not_migrated,
                   "Legacy throw action has no client_v1 typed request."),
        detail::cm("CM_TURN", 3010, "kCmTurn", "ActionIntent",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::cm("CM_WALK", 3011, "kCmWalk", "MoveIntent / ActionIntent",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::cm("CM_SITDOWN", 3012, "kCmSitDown", "",
                   LegacyProtocolMappingStatus::legacy_only,
                   "Legacy ident is defined, but client_v1 has no sit request."),
        detail::cm("CM_RUN", 3013, "kCmRun", "MoveIntent / ActionIntent",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::cm("CM_HIT", 3014, "kCmHit", "ActionIntent",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::cm("CM_HEAVYHIT", 3015, "kCmHeavyHit", "ActionIntent.legacy_ident",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::cm("CM_BIGHIT", 3016, "kCmBigHit", "ActionIntent.legacy_ident",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::cm("CM_SPELL", 3017, "kCmSpell", "SpellIntent",
                   LegacyProtocolMappingStatus::partial,
                   "Spell request is wired; detailed magic parity remains partial."),
        detail::cm("CM_POWERHIT", 3018, "kCmPowerHit", "ActionIntent.legacy_ident",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::cm("CM_LONGHIT", 3019, "kCmLongHit", "ActionIntent.legacy_ident",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::cm("CM_WIDEHIT", 3024, "kCmWideHit", "ActionIntent.legacy_ident",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::cm("CM_FIREHIT", 3025, "kCmFireHit", "ActionIntent.legacy_ident",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::cm("CM_SAY", 3030, "kCmSay", "ChatSend",
                   LegacyProtocolMappingStatus::partial,
                   "ChatSend exists; legacy channel command semantics are partial."),
        detail::cm("CM_CROSSHIT", 3035, "kCmCrossHit", "ActionIntent.legacy_ident",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::cm("CM_QUERYUSERNAME", 80, "kCmQueryUsername", "QueryActorNameRequest",
                   LegacyProtocolMappingStatus::planned,
                   "Needs target-name query UI and client_v1 bridge coverage."),
        detail::cm("CM_QUERYBAGITEMS", 81, "kCmQueryBagItems", "BagSnapshot",
                   LegacyProtocolMappingStatus::legacy_only,
                   "Legacy refresh request is decoded; client_v1 receives bag snapshots."),
        detail::cm("CM_QUERYUSERSTATE", 82, "", "SelfAbilityDetail",
                   LegacyProtocolMappingStatus::planned,
                   "Target user-state query is not exposed as a client_v1 request."),
        detail::cm("CM_DROPITEM", 1000, "kCmDropItem", "DropItemRequest",
                   LegacyProtocolMappingStatus::partial,
                   "Drop request is wired; full legacy UI/rollback parity is partial."),
        detail::cm("CM_PICKUP", 1001, "kCmPickup", "PickupIntent",
                   LegacyProtocolMappingStatus::partial,
                   "Pickup request is wired; ground item UI parity is partial."),
        detail::cm("CM_OPENDOOR", 1002, "", "MapDoorState",
                   LegacyProtocolMappingStatus::not_migrated,
                   "Door state can be received, but open-door request is not migrated."),
        detail::cm("CM_TAKEONITEM", 1003, "kCmTakeOnItem", "EquipItemRequest",
                   LegacyProtocolMappingStatus::partial,
                   "Equip request is wired; extended slot UI parity is partial."),
        detail::cm("CM_TAKEOFFITEM", 1004, "kCmTakeOffItem", "UnequipItemRequest",
                   LegacyProtocolMappingStatus::partial,
                   "Unequip request is wired; full rollback UI parity is partial."),
        detail::cm("CM_EXCHGTAKEONITEM", 1005, "kCmExchgTakeOnItem", "",
                   LegacyProtocolMappingStatus::legacy_only,
                   "Legacy swap-equip ident is defined, but client_v1 uses separate equip flows."),
        detail::cm("CM_EAT", 1006, "kCmEat", "UseItemIntent",
                   LegacyProtocolMappingStatus::partial,
                   "Use item is wired; full consumable result parity is partial."),
        detail::cm("CM_BUTCH", 1007, "", "ButchActorRequest",
                   LegacyProtocolMappingStatus::planned,
                   "Needs butch target selection UI and world loot authority."),
        detail::cm("CM_MAGICKEYCHANGE", 1008, "", "MagicKeyChangeRequest",
                   LegacyProtocolMappingStatus::partial,
                   "Key rebinding is wired through MagicList refreshes."),
        detail::cm("CM_SOFTCLOSE", 1009, "", "DisconnectReason",
                   LegacyProtocolMappingStatus::internal,
                   "Legacy soft-close control maps to connection shutdown behavior."),
        detail::cm("CM_CLICKNPC", 1010, "kCmClickNpc", "NpcClickRequest",
                   LegacyProtocolMappingStatus::partial,
                   "NPC click is wired; merchant follow-up parity is partial."),
        detail::cm("CM_MERCHANTDLGSELECT", 1011, "kCmMerchantDlgSelect",
                   "NpcDialogSelectRequest", LegacyProtocolMappingStatus::partial,
                   "Dialog link selection is wired; full business panel parity is partial."),
        detail::cm("CM_MERCHANTQUERYSELLPRICE", 1012, "kCmMerchantQuerySellPrice",
                   "MerchantSellPriceRequest", LegacyProtocolMappingStatus::partial,
                   "Sell-price request is wired for current merchant flow."),
        detail::cm("CM_USERSELLITEM", 1013, "kCmUserSellItem", "MerchantSellRequest",
                   LegacyProtocolMappingStatus::partial,
                   "Sell request is wired; legacy confirmation details are partial."),
        detail::cm("CM_USERBUYITEM", 1014, "kCmUserBuyItem", "MerchantBuyRequest",
                   LegacyProtocolMappingStatus::partial,
                   "Buy request is wired; legacy shop details are partial."),
        detail::cm("CM_USERGETDETAILITEM", 1015, "kCmUserGetDetailItem",
                   "DetailItemRequest", LegacyProtocolMappingStatus::planned,
                   "Needs detail goods panel request/response wiring."),
        detail::cm("CM_DROPGOLD", 1016, "kCmDropGold", "DropGoldRequest",
                   LegacyProtocolMappingStatus::partial,
                   "Drop gold is wired; amount-entry UI remains minimal."),
        detail::cm("CM_TEST", 1017, "", "",
                   LegacyProtocolMappingStatus::internal,
                   "Legacy diagnostic packet; no gameplay mapping."),
        detail::cm("CM_LOGINNOTICEOK", 1018, "", "LoginNoticeOk",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::cm("CM_GROUPMODE", 1019, "", "GroupModeRequest",
                   LegacyProtocolMappingStatus::partial,
                   "Group mode is mirrored by the client_v1 gateway registry."),
        detail::cm("CM_CREATEGROUP", 1020, "", "GroupCreateRequest",
                   LegacyProtocolMappingStatus::partial,
                   "Group create is wired to the online gateway registry."),
        detail::cm("CM_ADDGROUPMEMBER", 1021, "", "GroupAddMemberRequest",
                   LegacyProtocolMappingStatus::partial,
                   "Group add-member is wired to the online gateway registry."),
        detail::cm("CM_DELGROUPMEMBER", 1022, "", "GroupRemoveMemberRequest",
                   LegacyProtocolMappingStatus::partial,
                   "Group remove-member is wired to the online gateway registry."),
        detail::cm("CM_USERREPAIRITEM", 1023, "kCmUserRepairItem", "MerchantRepairRequest",
                   LegacyProtocolMappingStatus::partial,
                   "Repair request is wired; legacy confirmation details are partial."),
        detail::cm("CM_MERCHANTQUERYREPAIRCOST", 1024, "kCmMerchantQueryRepairCost",
                   "MerchantRepairPriceRequest", LegacyProtocolMappingStatus::partial,
                   "Repair-price request is wired for current merchant flow."),
        detail::cm("CM_DEALTRY", 1025, "kCmDealTry", "TradeTryRequest",
                   LegacyProtocolMappingStatus::partial,
                   "Trade open is wired; lock/confirm edge cases are partial."),
        detail::cm("CM_DEALADDITEM", 1026, "kCmDealAddItem", "TradeAddItemRequest",
                   LegacyProtocolMappingStatus::partial,
                   "Trade add-item is wired; item selection UI is minimal."),
        detail::cm("CM_DEALDELITEM", 1027, "kCmDealDelItem", "TradeRemoveItemRequest",
                   LegacyProtocolMappingStatus::partial,
                   "Trade remove-item is wired; item selection UI is minimal."),
        detail::cm("CM_DEALCANCEL", 1028, "kCmDealCancel", "TradeCancelRequest",
                   LegacyProtocolMappingStatus::partial,
                   "Trade cancel is wired through gateway session mirrors."),
        detail::cm("CM_DEALCHGGOLD", 1029, "kCmDealChangeGold", "TradeSetGoldRequest",
                   LegacyProtocolMappingStatus::partial,
                   "Trade gold is wired; amount-entry UI remains minimal."),
        detail::cm("CM_DEALEND", 1030, "kCmDealEnd", "TradeAcceptRequest",
                   LegacyProtocolMappingStatus::partial,
                   "Trade accept is wired; final outcome follows world authority."),
        detail::cm("CM_USERSTORAGEITEM", 1031, "kCmUserStorageItem", "StorageDepositRequest",
                   LegacyProtocolMappingStatus::partial,
                   "Storage deposit is wired for selected bag items."),
        detail::cm("CM_USERTAKEBACKSTORAGEITEM", 1032, "kCmUserTakeBackStorageItem",
                   "StorageWithdrawRequest", LegacyProtocolMappingStatus::partial,
                   "Storage withdraw is wired from the storage list."),
        detail::cm("CM_WANTMINIMAP", 1033, "", "MiniMapRequest",
                   LegacyProtocolMappingStatus::partial,
                   "Mini-map request/data path is wired; map parity is partial."),
        detail::cm("CM_USERMAKEDRUGITEM", 1034, "", "MakeDrugItemRequest",
                   LegacyProtocolMappingStatus::planned,
                   "Needs make-drug merchant UI and server command bridge."),
        detail::cm("CM_OPENGUILDDLG", 1035, "", "GuildOpenRequest",
                   LegacyProtocolMappingStatus::partial,
                   "Guild open is wired to gateway snapshots."),
        detail::cm("CM_GUILDHOME", 1036, "", "GuildHomeRequest",
                   LegacyProtocolMappingStatus::partial,
                   "Guild home request refreshes gateway guild state."),
        detail::cm("CM_GUILDMEMBERLIST", 1037, "", "GuildMemberListRequest",
                   LegacyProtocolMappingStatus::partial,
                   "Guild member-list request refreshes gateway guild state."),
        detail::cm("CM_GUILDADDMEMBER", 1038, "", "GuildAddMemberRequest",
                   LegacyProtocolMappingStatus::partial,
                   "Guild add-member updates gateway guild snapshots."),
        detail::cm("CM_GUILDDELMEMBER", 1039, "", "GuildRemoveMemberRequest",
                   LegacyProtocolMappingStatus::partial,
                   "Guild remove-member updates gateway guild snapshots."),
        detail::cm("CM_GUILDUPDATENOTICE", 1040, "", "GuildUpdateNoticeRequest",
                   LegacyProtocolMappingStatus::partial,
                   "Guild notice update is wired; editor UX parity is partial."),
        detail::cm("CM_GUILDUPDATERANKINFO", 1041, "", "GuildUpdateGradeRequest",
                   LegacyProtocolMappingStatus::partial,
                   "Guild rank update is wired; editor UX parity is partial."),
        detail::cm("CM_SPEEDHACKUSER", 1042, "", "SpeedHackReport",
                   LegacyProtocolMappingStatus::planned,
                   "Needs detection cadence and server audit policy."),
        detail::cm("CM_ADJUST_BONUS", 1043, "", "AdjustBonusRequest",
                   LegacyProtocolMappingStatus::planned,
                   "Needs bonus allocation UI and authoritative stat update flow."),
        detail::cm("CM_GUILDMAKEALLY", 1044, "", "",
                   LegacyProtocolMappingStatus::not_migrated,
                   "Guild alliance workflow is not migrated to client_v1."),
        detail::cm("CM_GUILDBREAKALLY", 1045, "", "",
                   LegacyProtocolMappingStatus::not_migrated,
                   "Guild alliance break workflow is not migrated to client_v1."),
        detail::cm("CM_FRIEND_ADD", 1046, "", "",
                   LegacyProtocolMappingStatus::not_migrated,
                   "Legacy friend system is not migrated to client_v1."),
        detail::cm("CM_FRIEND_DELETE", 1047, "", "",
                   LegacyProtocolMappingStatus::not_migrated,
                   "Legacy friend system is not migrated to client_v1."),
        detail::cm("CM_FRIEND_EDIT", 1048, "", "",
                   LegacyProtocolMappingStatus::not_migrated,
                   "Legacy friend system is not migrated to client_v1."),
        detail::cm("CM_FRIEND_LIST", 1049, "", "",
                   LegacyProtocolMappingStatus::not_migrated,
                   "Legacy friend system is not migrated to client_v1."),
        detail::cm("CM_TAG_ADD", 1050, "", "",
                   LegacyProtocolMappingStatus::not_migrated,
                   "Legacy tag system is not migrated to client_v1."),
        detail::cm("CM_TAG_DELETE", 1051, "", "",
                   LegacyProtocolMappingStatus::not_migrated,
                   "Legacy tag system is not migrated to client_v1."),
        detail::cm("CM_TAG_SETINFO", 1052, "", "",
                   LegacyProtocolMappingStatus::not_migrated,
                   "Legacy tag system is not migrated to client_v1."),
        detail::cm("CM_TAG_LIST", 1053, "", "",
                   LegacyProtocolMappingStatus::not_migrated,
                   "Legacy tag system is not migrated to client_v1."),
        detail::cm("CM_TAG_NOTREADCOUNT", 1054, "", "",
                   LegacyProtocolMappingStatus::not_migrated,
                   "Legacy tag system is not migrated to client_v1."),
        detail::cm("CM_TAG_REJECT_LIST", 1055, "", "",
                   LegacyProtocolMappingStatus::not_migrated,
                   "Legacy tag reject-list workflow is not migrated to client_v1."),
        detail::cm("CM_TAG_REJECT_ADD", 1056, "", "",
                   LegacyProtocolMappingStatus::not_migrated,
                   "Legacy tag reject-list workflow is not migrated to client_v1."),
        detail::cm("CM_TAG_REJECT_DELETE", 1057, "", "",
                   LegacyProtocolMappingStatus::not_migrated,
                   "Legacy tag reject-list workflow is not migrated to client_v1."),
        detail::cm("CM_CLIENT_CHECKTIME", 1100, "", "Ping / Pong",
                   LegacyProtocolMappingStatus::internal,
                   "Legacy client time-check is represented by Ping/Pong health checks."),
    }};

inline constexpr std::array<LegacyMessageMappingEntry, 220>
    kDelphiServerToClientMessageMappings{{
        detail::sm("SM_TEST", 1, "", "",
                   LegacyProtocolMappingStatus::internal,
                   "Legacy diagnostic packet; no gameplay mapping."),
        detail::sm("SM_STOPACTIONS", 2, "", "",
                   LegacyProtocolMappingStatus::legacy_only,
                   "Legacy stop-actions packet is not exposed as a client_v1 message."),
        detail::sm("SM_ACTION_MIN", 5, "", "",
                   LegacyProtocolMappingStatus::internal,
                   "Delphi action range marker, not a concrete packet."),
        detail::sm("SM_THROW", 5, "", "ActorAction",
                   LegacyProtocolMappingStatus::not_migrated,
                   "Legacy throw action is not migrated to client_v1."),
        detail::sm("SM_RUSH", 6, "legacy::kSmRush", "ActorAction",
                   LegacyProtocolMappingStatus::partial,
                   "ActorAction has rush kind; full legacy motion parity is partial."),
        detail::sm("SM_RUSHKUNG", 7, "legacy::kSmRushKung", "ActorAction",
                   LegacyProtocolMappingStatus::partial,
                   "ActorAction has rush-kung kind; full legacy motion parity is partial."),
        detail::sm("SM_FIREHIT", 8, "legacy::kSmFireHit", "ActorAction",
                   LegacyProtocolMappingStatus::partial,
                   "Attack ident is represented; skill-specific visuals remain partial."),
        detail::sm("SM_BACKSTEP", 9, "legacy::kSmBackStep", "ActorAction",
                   LegacyProtocolMappingStatus::partial,
                   "ActorAction has backstep kind; full legacy motion parity is partial."),
        detail::sm("SM_TURN", 10, "kSmTurn", "ActorUpsert / ActorAction",
                   LegacyProtocolMappingStatus::partial,
                   "Actor turn/upsert is represented; full spawn payload parity is partial."),
        detail::sm("SM_WALK", 11, "kSmWalk", "ActorAction",
                   LegacyProtocolMappingStatus::partial,
                   "Actor walk is represented; full legacy cadence parity is partial."),
        detail::sm("SM_SITDOWN", 12, "kSmSitDown", "",
                   LegacyProtocolMappingStatus::legacy_only,
                   "Legacy sitdown action has no client_v1 typed event."),
        detail::sm("SM_RUN", 13, "kSmRun", "ActorAction",
                   LegacyProtocolMappingStatus::partial,
                   "Actor run is represented; full legacy cadence parity is partial."),
        detail::sm("SM_HIT", 14, "legacy::kSmHit", "ActorAction",
                   LegacyProtocolMappingStatus::partial,
                   "Actor hit is represented; attack visual parity is partial."),
        detail::sm("SM_HEAVYHIT", 15, "legacy::kSmHeavyHit", "ActorAction",
                   LegacyProtocolMappingStatus::partial,
                   "Attack ident is represented; skill-specific visuals remain partial."),
        detail::sm("SM_BIGHIT", 16, "legacy::kSmBigHit", "ActorAction",
                   LegacyProtocolMappingStatus::partial,
                   "Attack ident is represented; skill-specific visuals remain partial."),
        detail::sm("SM_SPELL", 17, "kSmSpell", "ActorAction / ActorMagicFire",
                   LegacyProtocolMappingStatus::partial,
                   "Spell action/fire messages exist; detailed magic parity is partial."),
        detail::sm("SM_POWERHIT", 18, "legacy::kSmPowerHit", "ActorAction",
                   LegacyProtocolMappingStatus::partial,
                   "Attack ident is represented; skill-specific visuals remain partial."),
        detail::sm("SM_LONGHIT", 19, "legacy::kSmLongHit", "ActorAction",
                   LegacyProtocolMappingStatus::partial,
                   "Attack ident is represented; skill-specific visuals remain partial."),
        detail::sm("SM_DIGUP", 20, "legacy::kSmDigUp", "",
                   LegacyProtocolMappingStatus::legacy_only,
                   "Legacy dig-up monster action is not exposed as client_v1."),
        detail::sm("SM_DIGDOWN", 21, "legacy::kSmDigDown", "",
                   LegacyProtocolMappingStatus::legacy_only,
                   "Legacy dig-down monster action is not exposed as client_v1."),
        detail::sm("SM_FLYAXE", 22, "legacy::kSmFlyAxe", "ActorAction",
                   LegacyProtocolMappingStatus::legacy_only,
                   "Legacy fly-axe action is tracked as legacy animation data only."),
        detail::sm("SM_LIGHTING", 23, "legacy::kSmLighting", "ActorAction",
                   LegacyProtocolMappingStatus::legacy_only,
                   "Legacy lightning action is tracked as legacy animation data only."),
        detail::sm("SM_WIDEHIT", 24, "legacy::kSmWideHit", "ActorAction",
                   LegacyProtocolMappingStatus::partial,
                   "Attack ident is represented; skill-specific visuals remain partial."),
        detail::sm("SM_ACTION_MAX", 25, "", "",
                   LegacyProtocolMappingStatus::internal,
                   "Delphi action range marker, not a concrete packet."),
        detail::sm("SM_CROSSHIT", 35, "legacy::kSmCrossHit", "ActorAction",
                   LegacyProtocolMappingStatus::partial,
                   "Attack ident is represented; skill-specific visuals remain partial."),
        detail::sm("SM_ACTION2_MIN", 1000, "", "",
                   LegacyProtocolMappingStatus::internal,
                   "Delphi extended action range marker, not a concrete packet."),
        detail::sm("SM_ACTION2_MAX", 1099, "", "",
                   LegacyProtocolMappingStatus::internal,
                   "Delphi extended action range marker, not a concrete packet."),
        detail::sm("SM_DIE", 26, "", "ActorDeath",
                   LegacyProtocolMappingStatus::legacy_only,
                   "Delphi declares this alias separately from SM_DEATH; client_v1 uses ActorDeath."),
        detail::sm("SM_ALIVE", 27, "kSmAlive", "ActorUpsert",
                   LegacyProtocolMappingStatus::partial,
                   "Revive/alive state is represented; full animation parity is partial."),
        detail::sm("SM_MOVEFAIL", 28, "kSmMoveFail", "ActionAck / ActorAction",
                   LegacyProtocolMappingStatus::partial,
                   "Move rejection is represented through ack/state correction."),
        detail::sm("SM_HIDE", 29, "", "ActorRemove",
                   LegacyProtocolMappingStatus::legacy_only,
                   "Legacy hide state is folded into actor removal/visibility state."),
        detail::sm("SM_DISAPPEAR", 30, "kSmDisappear", "ActorRemove",
                   LegacyProtocolMappingStatus::partial,
                   "Actor removal is represented; all hide/ghost variants are partial."),
        detail::sm("SM_STRUCK", 31, "kSmStruck", "ActorVitals",
                   LegacyProtocolMappingStatus::partial,
                   "Damage/vitals are represented; struck animation parity is partial."),
        detail::sm("SM_DEATH", 32, "kSmDeath", "ActorDeath",
                   LegacyProtocolMappingStatus::partial,
                   "Death event is represented; corpse/animation details are partial."),
        detail::sm("SM_SKELETON", 33, "legacy::kSmSkeleton", "ActorDeath",
                   LegacyProtocolMappingStatus::legacy_only,
                   "Skeleton death variant is legacy animation data only."),
        detail::sm("SM_NOWDEATH", 34, "kSmNowDeath", "ActorDeath",
                   LegacyProtocolMappingStatus::partial,
                   "Immediate death event is represented; animation details are partial."),
        detail::sm("SM_HEAR", 40, "kSmHear", "ActorSay / ChatLine",
                   LegacyProtocolMappingStatus::partial,
                   "Nearby speech is represented; channel color semantics are partial."),
        detail::sm("SM_FEATURECHANGED", 41, "kSmFeatureChanged", "ActorIdentityUpdate",
                   LegacyProtocolMappingStatus::partial,
                   "Actor feature refresh is folded into ActorUpsert."),
        detail::sm("SM_USERNAME", 42, "kSmUsername", "ActorIdentityUpdate",
                   LegacyProtocolMappingStatus::partial,
                   "Actor name refresh is folded into ActorUpsert."),
        detail::sm("SM_WINEXP", 44, "kSmWinExp", "SelfAbility",
                   LegacyProtocolMappingStatus::partial,
                   "Experience changes are folded into ability refreshes."),
        detail::sm("SM_LEVELUP", 45, "kSmLevelUp", "SelfAbility / SelfAbilityDetail",
                   LegacyProtocolMappingStatus::partial,
                   "Level-up is represented through ability refreshes."),
        detail::sm("SM_DAYCHANGING", 46, "kSmDayChanging", "",
                   LegacyProtocolMappingStatus::legacy_only,
                   "Legacy day/night change is not exposed as a dedicated client_v1 message."),
        detail::sm("SM_LOGON", 50, "kSmLogon", "EnterWorldResult / WorldSnapshot",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::sm("SM_NEWMAP", 51, "kSmNewMap", "MapEntered",
                   LegacyProtocolMappingStatus::partial,
                   "Map change is represented; legacy description fields are partial."),
        detail::sm("SM_ABILITY", 52, "kSmAbility", "SelfAbility",
                   LegacyProtocolMappingStatus::partial,
                   "Ability summary is represented; all legacy counters are partial."),
        detail::sm("SM_HEALTHSPELLCHANGED", 53, "kSmHealthSpellChanged", "ActorVitals",
                   LegacyProtocolMappingStatus::partial,
                   "HP/MP update is represented through ActorVitals."),
        detail::sm("SM_MAPDESCRIPTION", 54, "kSmMapDescription", "MapDescription",
                   LegacyProtocolMappingStatus::partial,
                   "Legacy description text is represented as a map title."),
        detail::sm("SM_SYSMESSAGE", 100, "", "SysMessage / ChatLine",
                   LegacyProtocolMappingStatus::partial,
                   "System messages are represented; legacy colors/channels are partial."),
        detail::sm("SM_GROUPMESSAGE", 101, "", "ChatLine",
                   LegacyProtocolMappingStatus::partial,
                   "Group message text can be shown; channel semantics are partial."),
        detail::sm("SM_CRY", 102, "", "ChatLine",
                   LegacyProtocolMappingStatus::partial,
                   "Shout text can be shown; channel semantics are partial."),
        detail::sm("SM_WHISPER", 103, "", "ChatLine",
                   LegacyProtocolMappingStatus::partial,
                   "Whisper text can be shown; private chat workflow is partial."),
        detail::sm("SM_GUILDMESSAGE", 104, "", "ChatLine",
                   LegacyProtocolMappingStatus::partial,
                   "Guild message text can be shown; channel semantics are partial."),
        detail::sm("SM_ADDITEM", 200, "kSmAddItem", "InventoryAdd",
                   LegacyProtocolMappingStatus::partial,
                   "Inventory add updates the bag mirror; full UI parity is partial."),
        detail::sm("SM_BAGITEMS", 201, "kSmBagItems", "BagSnapshot",
                   LegacyProtocolMappingStatus::partial,
                   "Bag snapshot updates the mirror; full legacy layout parity is partial."),
        detail::sm("SM_DELITEM", 202, "kSmDelItem", "InventoryRemove",
                   LegacyProtocolMappingStatus::partial,
                   "Inventory remove updates the bag mirror."),
        detail::sm("SM_UPDATEITEM", 203, "kSmUpdateItem", "InventoryUpdate",
                   LegacyProtocolMappingStatus::partial,
                   "Inventory update refreshes the bag mirror."),
        detail::sm("SM_ADDMAGIC", 210, "kSmAddMagic", "MagicList",
                   LegacyProtocolMappingStatus::partial,
                   "Add-magic is folded into MagicList refreshes."),
        detail::sm("SM_SENDMYMAGIC", 211, "kSmSendMyMagic", "MagicList",
                   LegacyProtocolMappingStatus::partial,
                   "Magic list drives the state window magic page."),
        detail::sm("SM_DELMAGIC", 212, "kSmDelMagic", "MagicList",
                   LegacyProtocolMappingStatus::partial,
                   "Delete-magic is folded into MagicList refreshes."),
        detail::sm("SM_VERSION_AVAILABLE", 500, "", "ClientHello",
                   LegacyProtocolMappingStatus::internal,
                   "Legacy version accept is represented by the client_v1 handshake."),
        detail::sm("SM_VERSION_FAIL", 501, "", "DisconnectReason",
                   LegacyProtocolMappingStatus::internal,
                   "Legacy version rejection maps to connection/login failure handling."),
        detail::sm("SM_PASSWD_SUCCESS", 502, "kSmPasswdSuccess", "LoginResult / ServerList",
                   LegacyProtocolMappingStatus::partial,
                   "Login success exists; legacy follow-up messages are split."),
        detail::sm("SM_PASSWD_FAIL", 503, "kSmPasswdFail", "LoginResult",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::sm("SM_NEWID_SUCCESS", 504, "kSmNewIdSuccess", "CreateAccountResult",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::sm("SM_NEWID_FAIL", 505, "kSmNewIdFail", "CreateAccountResult",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::sm("SM_CHGPASSWD_SUCCESS", 506, "kSmChgPasswdSuccess",
                   "ChangePasswordResult", LegacyProtocolMappingStatus::implemented, ""),
        detail::sm("SM_CHGPASSWD_FAIL", 507, "kSmChgPasswdFail", "ChangePasswordResult",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::sm("SM_QUERYCHR", 520, "kSmQueryChr", "CharacterList",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::sm("SM_NEWCHR_SUCCESS", 521, "kSmNewChrSuccess", "CreateCharacterResult",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::sm("SM_NEWCHR_FAIL", 522, "kSmNewChrFail", "CreateCharacterResult",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::sm("SM_DELCHR_SUCCESS", 523, "kSmDelChrSuccess", "DeleteCharacterResult",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::sm("SM_DELCHR_FAIL", 524, "kSmDelChrFail", "DeleteCharacterResult",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::sm("SM_STARTPLAY", 525, "kSmStartPlay", "SelectCharacterResult",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::sm("SM_STARTFAIL", 526, "kSmStartFail", "SelectCharacterResult",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::sm("SM_QUERYCHR_FAIL", 527, "kSmQueryChrFail", "CharacterList",
                   LegacyProtocolMappingStatus::partial,
                   "Query failure is represented as a typed error/list result."),
        detail::sm("SM_OUTOFCONNECTION", 528, "kSmOutOfConnection", "DisconnectReason",
                   LegacyProtocolMappingStatus::partial,
                   "Disconnect notice exists; reconnect edge cases remain partial."),
        detail::sm("SM_PASSOK_SELECTSERVER", 529, "kSmPassOkSelectServer",
                   "LoginResult / ServerList", LegacyProtocolMappingStatus::partial,
                   "Login success and server list are split into typed messages."),
        detail::sm("SM_SELECTSERVER_OK", 530, "kSmSelectServerOk", "SelectServerResult",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::sm("SM_NEEDUPDATE_ACCOUNT", 531, "kSmNeedUpdateAccount",
                   "NeedUpdateAccount", LegacyProtocolMappingStatus::implemented, ""),
        detail::sm("SM_UPDATEID_SUCCESS", 532, "kSmUpdateIdSuccess", "UpdateAccountResult",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::sm("SM_UPDATEID_FAIL", 533, "kSmUpdateIdFail", "UpdateAccountResult",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::sm("SM_PASSOK_WRONGSSN", 534, "", "LoginResult",
                   LegacyProtocolMappingStatus::partial,
                   "Legacy wrong-SSN branch is folded into login result errors."),
        detail::sm("SM_NOT_IN_SERVICE", 535, "", "LoginResult",
                   LegacyProtocolMappingStatus::partial,
                   "Legacy not-in-service branch is folded into login result errors."),
        detail::sm("SM_DROPITEM_SUCCESS", 600, "kSmDropItemSuccess", "InventoryRemove",
                   LegacyProtocolMappingStatus::partial,
                   "Drop success is reflected by authoritative inventory updates."),
        detail::sm("SM_DROPITEM_FAIL", 601, "kSmDropItemFail", "SysMessage",
                   LegacyProtocolMappingStatus::partial,
                   "Drop failure surfaces as a system message."),
        detail::sm("SM_ITEMSHOW", 610, "kSmItemShow", "GroundItemAdd",
                   LegacyProtocolMappingStatus::partial,
                   "Ground item add reaches world state; sprite parity is partial."),
        detail::sm("SM_ITEMHIDE", 611, "kSmItemHide", "GroundItemRemove",
                   LegacyProtocolMappingStatus::partial,
                   "Ground item removal reaches world state."),
        detail::sm("SM_OPENDOOR_OK", 612, "kSmOpenDoorOk", "MapDoorState",
                   LegacyProtocolMappingStatus::partial,
                   "Open-door state is represented; request flow is not migrated."),
        detail::sm("SM_OPENDOOR_LOCK", 613, "kSmOpenDoorLock", "SysMessage",
                   LegacyProtocolMappingStatus::legacy_only,
                   "Locked-door result is not represented as a typed result."),
        detail::sm("SM_CLOSEDOOR", 614, "kSmCloseDoor", "MapDoorState",
                   LegacyProtocolMappingStatus::partial,
                   "Close-door state is represented."),
        detail::sm("SM_TAKEON_OK", 615, "kSmTakeOnOk", "EquipmentSnapshot",
                   LegacyProtocolMappingStatus::partial,
                   "Equip success is reflected by equipment snapshots."),
        detail::sm("SM_TAKEON_FAIL", 616, "kSmTakeOnFail", "SysMessage",
                   LegacyProtocolMappingStatus::partial,
                   "Equip failure surfaces through messages/rollback state."),
        detail::sm("SM_EXCHGTAKEON_OK", 617, "", "EquipmentSnapshot",
                   LegacyProtocolMappingStatus::legacy_only,
                   "Legacy swap-equip result is folded into snapshots when present."),
        detail::sm("SM_EXCHGTAKEON_FAIL", 618, "", "SysMessage",
                   LegacyProtocolMappingStatus::legacy_only,
                   "Legacy swap-equip failure is not a typed result."),
        detail::sm("SM_TAKEOFF_OK", 619, "kSmTakeOffOk", "EquipmentSnapshot",
                   LegacyProtocolMappingStatus::partial,
                   "Unequip success is reflected by equipment snapshots."),
        detail::sm("SM_TAKEOFF_FAIL", 620, "kSmTakeOffFail", "SysMessage",
                   LegacyProtocolMappingStatus::partial,
                   "Unequip failure surfaces through messages/rollback state."),
        detail::sm("SM_SENDUSEITEMS", 621, "kSmSendUseItems", "EquipmentSnapshot",
                   LegacyProtocolMappingStatus::partial,
                   "Equipment snapshot refreshes the local equipment mirror."),
        detail::sm("SM_WEIGHTCHANGED", 622, "kSmWeightChanged", "SelfAbility",
                   LegacyProtocolMappingStatus::partial,
                   "Weight changes are folded into ability refreshes."),
        detail::sm("SM_CLEAROBJECTS", 633, "kSmClearObjects", "WorldClearObjects",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::sm("SM_CHANGEMAP", 634, "kSmChangeMap", "MapChange",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::sm("SM_EAT_OK", 635, "kSmEatOk", "UseItemResult",
                   LegacyProtocolMappingStatus::partial,
                   "Use-item success exists; detailed item effects are partial."),
        detail::sm("SM_EAT_FAIL", 636, "kSmEatFail", "UseItemResult / SysMessage",
                   LegacyProtocolMappingStatus::partial,
                   "Use-item failure exists; legacy reason codes are partial."),
        detail::sm("SM_BUTCH", 637, "", "ActorAction",
                   LegacyProtocolMappingStatus::planned,
                   "Butch/harvest flow is not implemented in client_v1."),
        detail::sm("SM_MAGICFIRE", 638, "kSmMagicFire", "ActorMagicFire",
                   LegacyProtocolMappingStatus::partial,
                   "Magic-fire event is represented; effect parity is partial."),
        detail::sm("SM_MAGICFIRE_FAIL", 639, "kSmMagicFireFail", "ActorMagicFireFail",
                   LegacyProtocolMappingStatus::partial,
                   "Magic-fire failure is represented."),
        detail::sm("SM_MAGIC_LVEXP", 640, "kSmMagicLvExp", "MagicList",
                   LegacyProtocolMappingStatus::partial,
                   "Magic level/exp change is folded into MagicList refreshes."),
        detail::sm("SM_SOUND", 641, "", "",
                   LegacyProtocolMappingStatus::legacy_only,
                   "Legacy sound trigger is handled by local presentation rules, not protocol."),
        detail::sm("SM_DURACHANGE", 642, "kSmDuraChange", "DurabilityChange",
                   LegacyProtocolMappingStatus::partial,
                   "Durability changes update bag/equipment mirrors by make-index."),
        detail::sm("SM_MERCHANTSAY", 643, "kSmMerchantSay", "NpcDialog",
                   LegacyProtocolMappingStatus::partial,
                   "NPC dialog text/link parser exists; business panels are partial."),
        detail::sm("SM_MERCHANTDLGCLOSE", 644, "kSmMerchantDlgClose", "NpcDialogClose",
                   LegacyProtocolMappingStatus::partial,
                   "NPC dialog close is represented."),
        detail::sm("SM_SENDGOODSLIST", 645, "kSmSendGoodsList", "MerchantGoodsList",
                   LegacyProtocolMappingStatus::partial,
                   "Goods list drives the buy window; full shop parity is partial."),
        detail::sm("SM_SENDUSERSELL", 646, "kSmSendUserSell", "MerchantPriceResult",
                   LegacyProtocolMappingStatus::partial,
                   "Sell selection is represented by price result state."),
        detail::sm("SM_SENDBUYPRICE", 647, "kSmSendBuyPrice", "MerchantPriceResult",
                   LegacyProtocolMappingStatus::legacy_only,
                   "Legacy buy-price result is not a dedicated client_v1 response."),
        detail::sm("SM_USERSELLITEM_OK", 648, "kSmUserSellItemOk", "MerchantPriceResult",
                   LegacyProtocolMappingStatus::partial,
                   "Sell success is reflected by inventory/gold and merchant state."),
        detail::sm("SM_USERSELLITEM_FAIL", 649, "kSmUserSellItemFail", "SysMessage",
                   LegacyProtocolMappingStatus::partial,
                   "Sell failure surfaces as a system/merchant message."),
        detail::sm("SM_BUYITEM_SUCCESS", 650, "kSmBuyItemSuccess", "InventoryAdd",
                   LegacyProtocolMappingStatus::partial,
                   "Buy success is reflected by inventory/gold updates."),
        detail::sm("SM_BUYITEM_FAIL", 651, "kSmBuyItemFail", "SysMessage",
                   LegacyProtocolMappingStatus::partial,
                   "Buy failure surfaces as a system/merchant message."),
        detail::sm("SM_SENDDETAILGOODSLIST", 652, "kSmSendDetailGoodsList",
                   "DetailGoodsList", LegacyProtocolMappingStatus::planned,
                   "Needs detail-goods panel state and gateway translation."),
        detail::sm("SM_GOLDCHANGED", 653, "kSmGoldChanged", "SelfAbility",
                   LegacyProtocolMappingStatus::partial,
                   "Gold changes are folded into ability refreshes."),
        detail::sm("SM_CHANGELIGHT", 654, "", "ActorUpsert",
                   LegacyProtocolMappingStatus::legacy_only,
                   "Legacy light changes are folded into actor state where available."),
        detail::sm("SM_LAMPCHANGEDURA", 655, "", "DurabilityChange",
                   LegacyProtocolMappingStatus::legacy_only,
                   "Legacy lamp durability is not represented as a dedicated typed result."),
        detail::sm("SM_CHANGENAMECOLOR", 656, "", "SelfAbilityDetail / ActorUpsert",
                   LegacyProtocolMappingStatus::partial,
                   "Name color is represented in detail/actor state when available."),
        detail::sm("SM_CHARSTATUSCHANGED", 657, "kSmCharStatusChanged", "ActorIdentityUpdate",
                   LegacyProtocolMappingStatus::partial,
                   "Character status changes are folded into actor state."),
        detail::sm("SM_SENDNOTICE", 658, "", "Notice",
                   LegacyProtocolMappingStatus::implemented, ""),
        detail::sm("SM_GROUPMODECHANGED", 659, "", "GroupState",
                   LegacyProtocolMappingStatus::partial,
                   "Group mode is represented in GroupState."),
        detail::sm("SM_CREATEGROUP_OK", 660, "", "GroupState",
                   LegacyProtocolMappingStatus::partial,
                   "Group create success is represented in GroupState."),
        detail::sm("SM_CREATEGROUP_FAIL", 661, "", "SysMessage",
                   LegacyProtocolMappingStatus::partial,
                   "Group create failure surfaces as a system message."),
        detail::sm("SM_GROUPADDMEM_OK", 662, "", "GroupState",
                   LegacyProtocolMappingStatus::partial,
                   "Group add-member success is represented in GroupState."),
        detail::sm("SM_GROUPDELMEM_OK", 663, "", "GroupState",
                   LegacyProtocolMappingStatus::partial,
                   "Group remove-member success is represented in GroupState."),
        detail::sm("SM_GROUPADDMEM_FAIL", 664, "", "SysMessage",
                   LegacyProtocolMappingStatus::partial,
                   "Group add-member failure surfaces as a system message."),
        detail::sm("SM_GROUPDELMEM_FAIL", 665, "", "SysMessage",
                   LegacyProtocolMappingStatus::partial,
                   "Group remove-member failure surfaces as a system message."),
        detail::sm("SM_GROUPCANCEL", 666, "", "GroupState",
                   LegacyProtocolMappingStatus::partial,
                   "Group cancellation is represented by clearing GroupState."),
        detail::sm("SM_GROUPMEMBERS", 667, "", "GroupState",
                   LegacyProtocolMappingStatus::partial,
                   "Group members drive the group panel."),
        detail::sm("SM_SENDUSERREPAIR", 668, "kSmSendUserRepair",
                   "MerchantRepairPriceResult", LegacyProtocolMappingStatus::partial,
                   "Repair selection is represented by repair-price state."),
        detail::sm("SM_USERREPAIRITEM_OK", 669, "kSmUserRepairItemOk",
                   "MerchantRepairPriceResult", LegacyProtocolMappingStatus::partial,
                   "Repair success is reflected by item durability/merchant state."),
        detail::sm("SM_USERREPAIRITEM_FAIL", 670, "kSmUserRepairItemFail", "SysMessage",
                   LegacyProtocolMappingStatus::partial,
                   "Repair failure surfaces as a system/merchant message."),
        detail::sm("SM_SENDREPAIRCOST", 671, "kSmSendRepairCost",
                   "MerchantRepairPriceResult", LegacyProtocolMappingStatus::partial,
                   "Repair cost is represented by repair-price result state."),
        detail::sm("SM_DEALMENU", 673, "kSmDealMenu", "TradeState",
                   LegacyProtocolMappingStatus::partial,
                   "Trade menu opens the TradeState panel."),
        detail::sm("SM_DEALTRY_FAIL", 674, "kSmDealTryFail", "SysMessage",
                   LegacyProtocolMappingStatus::partial,
                   "Trade open failure surfaces as a system/trade message."),
        detail::sm("SM_DEALADDITEM_OK", 675, "kSmDealAddItemOk", "TradeState",
                   LegacyProtocolMappingStatus::partial,
                   "Trade add success is represented by refreshed TradeState."),
        detail::sm("SM_DEALADDITEM_FAIL", 676, "kSmDealAddItemFail", "SysMessage",
                   LegacyProtocolMappingStatus::partial,
                   "Trade add failure surfaces as a system/trade message."),
        detail::sm("SM_DEALDELITEM_OK", 677, "kSmDealDelItemOk", "TradeState",
                   LegacyProtocolMappingStatus::partial,
                   "Trade remove success is represented by refreshed TradeState."),
        detail::sm("SM_DEALDELITEM_FAIL", 678, "kSmDealDelItemFail", "SysMessage",
                   LegacyProtocolMappingStatus::partial,
                   "Trade remove failure surfaces as a system/trade message."),
        detail::sm("SM_DEALCANCEL", 681, "kSmDealCancel", "TradeState",
                   LegacyProtocolMappingStatus::partial,
                   "Trade cancel clears TradeState on both peers."),
        detail::sm("SM_DEALREMOTEADDITEM", 682, "kSmDealRemoteAddItem", "TradeState",
                   LegacyProtocolMappingStatus::partial,
                   "Remote add is represented by refreshed TradeState."),
        detail::sm("SM_DEALREMOTEDELITEM", 683, "kSmDealRemoteDelItem", "TradeState",
                   LegacyProtocolMappingStatus::partial,
                   "Remote remove is represented by refreshed TradeState."),
        detail::sm("SM_DEALCHGGOLD_OK", 684, "kSmDealChangeGoldOk", "TradeState",
                   LegacyProtocolMappingStatus::partial,
                   "Local trade gold success is represented by TradeState."),
        detail::sm("SM_DEALCHGGOLD_FAIL", 685, "kSmDealChangeGoldFail", "SysMessage",
                   LegacyProtocolMappingStatus::partial,
                   "Trade gold failure surfaces as a system/trade message."),
        detail::sm("SM_DEALREMOTECHGGOLD", 686, "kSmDealRemoteChangeGold", "TradeState",
                   LegacyProtocolMappingStatus::partial,
                   "Remote trade gold change is represented by TradeState."),
        detail::sm("SM_DEALSUCCESS", 687, "kSmDealSuccess", "TradeState",
                   LegacyProtocolMappingStatus::partial,
                   "Trade success clears TradeState after authoritative updates."),
        detail::sm("SM_SENDUSERSTORAGEITEM", 700, "kSmSendUserStorageItem", "StorageList",
                   LegacyProtocolMappingStatus::partial,
                   "Storage open state is represented by StorageList."),
        detail::sm("SM_STORAGE_OK", 701, "kSmStorageOk", "StorageList",
                   LegacyProtocolMappingStatus::partial,
                   "Storage deposit success is reflected by storage/bag refreshes."),
        detail::sm("SM_STORAGE_FULL", 702, "kSmStorageFull", "SysMessage",
                   LegacyProtocolMappingStatus::partial,
                   "Storage-full failure surfaces as a system/storage message."),
        detail::sm("SM_STORAGE_FAIL", 703, "kSmStorageFail", "SysMessage",
                   LegacyProtocolMappingStatus::partial,
                   "Storage failure surfaces as a system/storage message."),
        detail::sm("SM_SAVEITEMLIST", 704, "kSmSaveItemList", "StorageList",
                   LegacyProtocolMappingStatus::partial,
                   "Storage item list drives the storage window."),
        detail::sm("SM_TAKEBACKSTORAGEITEM_OK", 705, "kSmTakeBackStorageItemOk",
                   "StorageList", LegacyProtocolMappingStatus::partial,
                   "Storage withdraw success is reflected by storage/bag refreshes."),
        detail::sm("SM_TAKEBACKSTORAGEITEM_FAIL", 706, "kSmTakeBackStorageItemFail",
                   "SysMessage", LegacyProtocolMappingStatus::partial,
                   "Storage withdraw failure surfaces as a system/storage message."),
        detail::sm("SM_TAKEBACKSTORAGEITEM_FULLBAG", 707,
                   "kSmTakeBackStorageItemFullBag", "SysMessage",
                   LegacyProtocolMappingStatus::partial,
                   "Full-bag withdraw failure surfaces as a system/storage message."),
        detail::sm("SM_AREASTATE", 708, "kSmAreaState", "",
                   LegacyProtocolMappingStatus::legacy_only,
                   "Legacy area-state value is not exposed as a client_v1 message."),
        detail::sm("SM_DELITEMS", 709, "", "InventoryClearRange",
                   LegacyProtocolMappingStatus::partial,
                   "Inventory clear-range updates the bag mirror."),
        detail::sm("SM_READMINIMAP_OK", 710, "", "MiniMapData",
                   LegacyProtocolMappingStatus::partial,
                   "Mini-map data drives the mini-map panel."),
        detail::sm("SM_READMINIMAP_FAIL", 711, "", "MiniMapData",
                   LegacyProtocolMappingStatus::partial,
                   "Mini-map failure is represented by MiniMapData.success=false."),
        detail::sm("SM_SENDUSERMAKEDRUGITEMLIST", 712, "", "MakeDrugList",
                   LegacyProtocolMappingStatus::planned,
                   "Needs make-drug merchant panel state and gateway translation."),
        detail::sm("SM_MAKEDRUG_SUCCESS", 713, "", "MakeDrugResult",
                   LegacyProtocolMappingStatus::planned,
                   "Needs make-drug request/result mapping."),
        detail::sm("SM_MAKEDRUG_FAIL", 714, "", "MakeDrugResult",
                   LegacyProtocolMappingStatus::planned,
                   "Needs make-drug request/result mapping."),
        detail::sm("SM_ALLOWPOWERHIT", 715, "", "ActorAction",
                   LegacyProtocolMappingStatus::legacy_only,
                   "Legacy power-hit permission is not a dedicated client_v1 message."),
        detail::sm("SM_NORMALEFFECT", 716, "", "ActorAction",
                   LegacyProtocolMappingStatus::legacy_only,
                   "Normal effect is not exposed as a dedicated client_v1 message."),
        detail::sm("SM_CHANGEGUILDNAME", 750, "", "GuildState",
                   LegacyProtocolMappingStatus::partial,
                   "Guild name changes are represented by refreshed GuildState."),
        detail::sm("SM_SENDUSERSTATE", 751, "", "SelfAbilityDetail",
                   LegacyProtocolMappingStatus::partial,
                   "Detailed ability state drives the state window."),
        detail::sm("SM_SUBABILITY", 752, "kSmSubAbility", "SelfAbilityDetail",
                   LegacyProtocolMappingStatus::partial,
                   "Sub-ability details are folded into SelfAbilityDetail."),
        detail::sm("SM_OPENGUILDDLG", 753, "", "GuildState",
                   LegacyProtocolMappingStatus::partial,
                   "Guild dialog state drives the guild panel."),
        detail::sm("SM_OPENGUILDDLG_FAIL", 754, "", "SysMessage",
                   LegacyProtocolMappingStatus::partial,
                   "Guild open failure surfaces as a system/guild message."),
        detail::sm("SM_SENDGUILDHOME", 755, "", "GuildState",
                   LegacyProtocolMappingStatus::partial,
                   "Guild home data is represented by GuildState."),
        detail::sm("SM_SENDGUILDMEMBERLIST", 756, "", "GuildState",
                   LegacyProtocolMappingStatus::partial,
                   "Guild member list is represented by GuildState."),
        detail::sm("SM_GUILDADDMEMBER_OK", 757, "", "GuildState",
                   LegacyProtocolMappingStatus::partial,
                   "Guild add success is represented by refreshed GuildState."),
        detail::sm("SM_GUILDADDMEMBER_FAIL", 758, "", "SysMessage",
                   LegacyProtocolMappingStatus::partial,
                   "Guild add failure surfaces as a system/guild message."),
        detail::sm("SM_GUILDDELMEMBER_OK", 759, "", "GuildState",
                   LegacyProtocolMappingStatus::partial,
                   "Guild remove success is represented by refreshed GuildState."),
        detail::sm("SM_GUILDDELMEMBER_FAIL", 760, "", "SysMessage",
                   LegacyProtocolMappingStatus::partial,
                   "Guild remove failure surfaces as a system/guild message."),
        detail::sm("SM_GUILDRANKUPDATE_FAIL", 761, "", "SysMessage",
                   LegacyProtocolMappingStatus::partial,
                   "Guild rank update failure surfaces as a system/guild message."),
        detail::sm("SM_BUILDGUILD_OK", 762, "", "GuildState",
                   LegacyProtocolMappingStatus::legacy_only,
                   "Build-guild result is not exposed as a dedicated client_v1 flow."),
        detail::sm("SM_BUILDGUILD_FAIL", 763, "", "SysMessage",
                   LegacyProtocolMappingStatus::legacy_only,
                   "Build-guild failure is not exposed as a dedicated client_v1 flow."),
        detail::sm("SM_DONATE_FAIL", 764, "", "SysMessage",
                   LegacyProtocolMappingStatus::not_migrated,
                   "Guild donation flow is not migrated to client_v1."),
        detail::sm("SM_DONATE_OK", 765, "", "GuildState",
                   LegacyProtocolMappingStatus::not_migrated,
                   "Guild donation flow is not migrated to client_v1."),
        detail::sm("SM_MYSTATUS", 766, "", "SelfAbility",
                   LegacyProtocolMappingStatus::partial,
                   "Hunger/status is folded into ability state."),
        detail::sm("SM_MENU_OK", 767, "", "NpcDialog",
                   LegacyProtocolMappingStatus::legacy_only,
                   "Legacy menu-ok dialog is not a dedicated client_v1 message."),
        detail::sm("SM_GUILDMAKEALLY_OK", 768, "", "GuildState",
                   LegacyProtocolMappingStatus::not_migrated,
                   "Guild alliance workflow is not migrated to client_v1."),
        detail::sm("SM_GUILDMAKEALLY_FAIL", 769, "", "SysMessage",
                   LegacyProtocolMappingStatus::not_migrated,
                   "Guild alliance workflow is not migrated to client_v1."),
        detail::sm("SM_GUILDBREAKALLY_OK", 770, "", "GuildState",
                   LegacyProtocolMappingStatus::not_migrated,
                   "Guild alliance break workflow is not migrated to client_v1."),
        detail::sm("SM_GUILDBREAKALLY_FAIL", 771, "", "SysMessage",
                   LegacyProtocolMappingStatus::not_migrated,
                   "Guild alliance break workflow is not migrated to client_v1."),
        detail::sm("SM_DLGMSG", 772, "", "NpcDialog",
                   LegacyProtocolMappingStatus::legacy_only,
                   "Generic legacy dialog message is not a dedicated typed protocol."),
        detail::sm("SM_SPACEMOVE_HIDE", 800, "kSmSpaceMoveHide", "ActorRemove",
                   LegacyProtocolMappingStatus::partial,
                   "Space-move hide is represented through visibility updates."),
        detail::sm("SM_SPACEMOVE_SHOW", 801, "kSmSpaceMoveShow", "ActorUpsert",
                   LegacyProtocolMappingStatus::partial,
                   "Space-move show is represented through actor upserts."),
        detail::sm("SM_RECONNECT", 802, "", "ReconnectResult",
                   LegacyProtocolMappingStatus::planned,
                   "Dedicated reconnect result is still planned."),
        detail::sm("SM_GHOST", 803, "", "ActorRemove",
                   LegacyProtocolMappingStatus::legacy_only,
                   "Ghost visibility is not exposed as a dedicated client_v1 message."),
        detail::sm("SM_SHOWEVENT", 804, "", "ActorUpsert",
                   LegacyProtocolMappingStatus::legacy_only,
                   "Legacy event actor show is not exposed as a dedicated client_v1 message."),
        detail::sm("SM_HIDEEVENT", 805, "", "ActorRemove",
                   LegacyProtocolMappingStatus::legacy_only,
                   "Legacy event actor hide is not exposed as a dedicated client_v1 message."),
        detail::sm("SM_SPACEMOVE_HIDE2", 806, "kSmSpaceMoveHide2", "ActorRemove",
                   LegacyProtocolMappingStatus::partial,
                   "Space-move hide variant is represented through visibility updates."),
        detail::sm("SM_SPACEMOVE_SHOW2", 807, "kSmSpaceMoveShow2", "ActorUpsert",
                   LegacyProtocolMappingStatus::partial,
                   "Space-move show variant is represented through actor upserts."),
        detail::sm("SM_TIMECHECK_MSG", 810, "", "Ping / Pong",
                   LegacyProtocolMappingStatus::internal,
                   "Legacy anti-speed time check is represented by connection health checks."),
        detail::sm("SM_ADJUST_BONUS", 811, "", "AdjustBonusState",
                   LegacyProtocolMappingStatus::planned,
                   "Needs bonus allocation state and UI."),
        detail::sm("SM_FRIEND_DELETE", 812, "", "",
                   LegacyProtocolMappingStatus::not_migrated,
                   "Legacy friend system is not migrated to client_v1."),
        detail::sm("SM_FRIEND_INFO", 813, "", "",
                   LegacyProtocolMappingStatus::not_migrated,
                   "Legacy friend system is not migrated to client_v1."),
        detail::sm("SM_FRIEND_RESULT", 814, "", "",
                   LegacyProtocolMappingStatus::not_migrated,
                   "Legacy friend system is not migrated to client_v1."),
        detail::sm("SM_TAG_ALARM", 815, "", "",
                   LegacyProtocolMappingStatus::not_migrated,
                   "Legacy tag system is not migrated to client_v1."),
        detail::sm("SM_TAG_LIST", 816, "", "",
                   LegacyProtocolMappingStatus::not_migrated,
                   "Legacy tag system is not migrated to client_v1."),
        detail::sm("SM_TAG_INFO", 817, "", "",
                   LegacyProtocolMappingStatus::not_migrated,
                   "Legacy tag system is not migrated to client_v1."),
        detail::sm("SM_TAG_REJECT_LIST", 818, "", "",
                   LegacyProtocolMappingStatus::not_migrated,
                   "Legacy tag reject-list workflow is not migrated to client_v1."),
        detail::sm("SM_TAG_REJECT_ADD", 819, "", "",
                   LegacyProtocolMappingStatus::not_migrated,
                   "Legacy tag reject-list workflow is not migrated to client_v1."),
        detail::sm("SM_TAG_REJECT_DELETE", 820, "", "",
                   LegacyProtocolMappingStatus::not_migrated,
                   "Legacy tag reject-list workflow is not migrated to client_v1."),
        detail::sm("SM_TAG_RESULT", 821, "", "",
                   LegacyProtocolMappingStatus::not_migrated,
                   "Legacy tag system is not migrated to client_v1."),
        detail::sm("SM_USER_INFO", 822, "", "",
                   LegacyProtocolMappingStatus::not_migrated,
                   "Legacy user-info/social packet is not migrated to client_v1."),
        detail::sm("SM_OPENHEALTH", 1100, "", "ActorVitals",
                   LegacyProtocolMappingStatus::legacy_only,
                   "Legacy floating health gauge open is presentation state only."),
        detail::sm("SM_CLOSEHEALTH", 1101, "", "ActorVitals",
                   LegacyProtocolMappingStatus::legacy_only,
                   "Legacy floating health gauge close is presentation state only."),
        detail::sm("SM_BREAKWEAPON", 1102, "kSmBreakWeapon", "SysMessage",
                   LegacyProtocolMappingStatus::legacy_only,
                   "Weapon break notification is not a dedicated typed result."),
        detail::sm("SM_INSTANCEHEALGUAGE", 1103, "", "ActorVitals",
                   LegacyProtocolMappingStatus::legacy_only,
                   "Instant health gauge update is folded into ActorVitals where available."),
        detail::sm("SM_CHANGEFACE", 1104, "", "ActorUpsert",
                   LegacyProtocolMappingStatus::legacy_only,
                   "Face changes are folded into actor feature state when available."),
        detail::sm("SM_NEXTTIME_PASSWORD", 1105, "", "LoginResult",
                   LegacyProtocolMappingStatus::legacy_only,
                   "Legacy next-time-password prompt is not a dedicated client_v1 flow."),
        detail::sm("SM_CHECK_CLIENTVALID", 1106, "", "",
                   LegacyProtocolMappingStatus::internal,
                   "Legacy client checksum challenge is not exposed to client_v1."),
        detail::sm("SM_PLAYDICE", 1200, "", "",
                   LegacyProtocolMappingStatus::not_migrated,
                   "Legacy dice mini-game packet is not migrated to client_v1."),
        detail::sm("SM_GROUPPOS", 1312, "", "ActorStateDelta",
                   LegacyProtocolMappingStatus::legacy_only,
                   "Legacy group position overlay is not a dedicated client_v1 message."),
    }};

// ====================================================================
// Migration status summary (as of PR-8 protocol mapping audit):
//   Send mappings:    11 implemented, 38 partial, 6 planned, 2 internal = 57
//   Receive mappings:  5 implemented, 30 partial, 4 planned, 0 internal = 39
//   Scene transitions: 11 implemented, 2 partial, 0 planned, 0 internal = 13
//   Legacy CM constants: 87 audited from Source/Common/Grobal2.pas
//   Legacy SM constants: 220 audited from Source/Common/Grobal2.pas
//
// All legacy Delphi client functions and protocol constants are accounted
// for. Partial entries have core functionality working; details and edge
// cases are tracked. Missing client_v1 equivalents are explicitly marked.
// ====================================================================
// 客户端发送消息映射表（57 条）
// 列出所有从 Delphi 客户端发送到服务端的消息及其新版映射
// ====================================================================
inline constexpr std::array<MappingEntry, 57> kDelphiSendMappings{{
    {"SendSocket", "ProtocolClient::send / client_v1 frame", "transport", MigrationStatus::internal,
     "Legacy text framing is replaced by length-prefixed client_v1 frames."},
    {"SendClientMessage", "client_v1 typed messages", "transport", MigrationStatus::internal,
     "Generic CM envelope is replaced by typed payloads."},
    {"CM_CLICKNPC", "NpcClickRequest", "npc", MigrationStatus::partial,
     "WorldScene sends NPC click intent for ActorType::npc; merchant/shop follow-up windows remain planned."},
    {"SendVersionNumber", "ClientHello", "session", MigrationStatus::implemented,
     "client_build and resource_revision carry the version handshake."},
    {"SendLogin", "LoginRequest", "login", MigrationStatus::implemented, ""},
    {"SendNewAccount", "CreateAccountRequest", "account", MigrationStatus::implemented,
     "Carries the legacy profile fields through AccountProfile."},
    {"SendUpdateAccount", "UpdateAccountRequest", "account", MigrationStatus::implemented,
     "Used after NeedUpdateAccount to complete legacy profile details."},
    {"SendSelectServer", "SelectServerRequest", "server_select", MigrationStatus::implemented, ""},
    {"SendChgPw", "ChangePasswordRequest", "account", MigrationStatus::implemented, ""},
    {"SendNewChr", "CreateCharacterRequest", "character", MigrationStatus::implemented, ""},
    {"SendQueryChr", "CharacterListRequest", "character", MigrationStatus::implemented,
     "First request after server selection carries the lobby token."},
    {"SendDelChr", "DeleteCharacterRequest", "character", MigrationStatus::implemented, ""},
    {"SendSelChr", "SelectCharacterRequest", "character", MigrationStatus::implemented, ""},
    {"SendRunLogin", "EnterWorldRequest + LoginNoticeOk", "world_entry",
     MigrationStatus::implemented,
     "Certification is represented by enter_world_token; CM_LOGINNOTICEOK is LoginNoticeOk."},
    {"SendSay", "ChatSend", "chat", MigrationStatus::partial,
     "World chat input supports Enter/Space/@/!/slash prefixes; complete channel semantics remain server-side/planned."},
    {"SendActMsg", "ActionIntent", "action", MigrationStatus::partial,
     "Turn/walk/run/attack now share the legacy action-lock path; sit and special idents are still partial."},
    {"SendSpellMsg", "SpellIntent", "combat", MigrationStatus::partial,
     "Shortcut spell intent and action-lock timing exist; detailed magic effects remain partial."},
    {"SendQueryUserName", "QueryActorNameRequest", "actor", MigrationStatus::planned,
     "Needs client query UI and server/client_v1 bridge coverage before implementation."},
    {"SendDropItem", "DropItemRequest", "inventory", MigrationStatus::partial,
     "Bag-item drop requests are wired with local pending rollback; equipment must be unequipped before dropping."},
    {"SendPickup", "PickupIntent", "inventory", MigrationStatus::partial,
     "Client can request pickup at the player's tile; ground item UI remains planned."},
    {"SendTakeOnItem", "EquipItemRequest", "inventory", MigrationStatus::partial,
     "Bag-to-equipment requests are wired; extended equipment slots remain visually hidden."},
    {"SendTakeOffItem", "UnequipItemRequest", "inventory", MigrationStatus::partial,
     "Equipment-to-bag requests are wired with pending rollback."},
    {"SendEat", "UseItemIntent", "inventory", MigrationStatus::partial,
     "Numeric slots can request consumable use; inventory mirror and rollback UI remain planned."},
    {"SendButchAnimal", "ButchActorRequest", "world", MigrationStatus::planned,
     "Needs butch target selection UI and world loot authority before implementation."},
    {"SendMagicKeyChange", "MagicKeyChangeRequest", "magic", MigrationStatus::partial,
     "State window can send key rebinding requests; server authority still arrives through MagicList refreshes."},
    {"SendMerchantDlgSelect", "NpcDialogSelectRequest", "npc", MigrationStatus::partial,
     "DMerchantDlg text-link selection is sent; merchant goods/storage/trade commands remain later phases."},
    {"SendQueryPrice", "MerchantSellPriceRequest", "merchant", MigrationStatus::partial,
     "Sell-price query is wired for the current merchant sell flow."},
    {"SendQueryRepairCost", "MerchantRepairPriceRequest", "merchant", MigrationStatus::partial,
     "Repair-price query is wired for bag-item repair selection."},
    {"SendSellItem", "MerchantSellRequest", "merchant", MigrationStatus::partial,
     "Sell confirmation is wired after a successful price result."},
    {"SendRepairItem", "MerchantRepairRequest", "merchant", MigrationStatus::partial,
     "Repair confirmation is wired after a successful repair price result."},
    {"SendStorageItem", "StorageDepositRequest", "storage", MigrationStatus::partial,
     "Storage deposit from selected bag items is wired."},
    {"SendGetDetailItem", "DetailItemRequest", "merchant", MigrationStatus::planned,
     "Needs detail-goods panel request/response wiring before implementation."},
    {"SendBuyItem", "MerchantBuyRequest", "merchant", MigrationStatus::partial,
     "Merchant buy request is wired from the goods list."},
    {"SendTakeBackStorageItem", "StorageWithdrawRequest", "storage", MigrationStatus::partial,
     "Storage withdraw request is wired from the storage list."},
    {"SendMakeDrugItem", "MakeDrugItemRequest", "merchant", MigrationStatus::planned,
     "Needs make-drug merchant list, selection UI, and server command bridge."},
    {"SendDropGold", "DropGoldRequest", "inventory", MigrationStatus::partial,
     "client_v1 wire and gateway bridge are implemented; amount-entry UI remains minimal."},
    {"SendGroupMode", "GroupModeRequest", "group", MigrationStatus::partial,
     "Group allow/invite mode is wired from the group panel and mirrored by the gateway registry."},
    {"SendCreateGroup", "GroupCreateRequest", "group", MigrationStatus::partial,
     "Create-group request is wired to the focused target and gateway online group registry."},
    {"SendWantMiniMap", "MiniMapRequest", "map", MigrationStatus::partial,
     "Mini-map request and MiniMapData rendering are wired."},
    {"SendDealTry", "TradeTryRequest", "trade", MigrationStatus::partial,
     "Trade open request is wired; client_v1 gateway now mirrors both online peers while Delphi lock/confirm edge cases remain partial."},
    {"SendGuildDlg", "GuildOpenRequest", "guild", MigrationStatus::partial,
     "Guild panel open request is wired to the gateway guild snapshot; full Delphi guild management remains partial."},
    {"SendCancelDeal", "TradeCancelRequest", "trade", MigrationStatus::partial,
     "Trade cancel request is wired and closes both client_v1 peer windows through the gateway session mirror."},
    {"SendAddDealItem", "TradeAddItemRequest", "trade", MigrationStatus::partial,
     "Selected bag item add is mirrored to the peer trade state before world authority removes it from the bag."},
    {"SendDelDealItem", "TradeRemoveItemRequest", "trade", MigrationStatus::partial,
     "Protocol and gateway rollback path exist; the panel still uses minimal item selection."},
    {"SendChangeDealGold", "TradeSetGoldRequest", "trade", MigrationStatus::partial,
     "Gold request is wired and clamped by the gateway; amount-entry UI remains minimal."},
    {"SendDealEnd", "TradeAcceptRequest", "trade", MigrationStatus::partial,
     "Accept request is mirrored to both peers; final success/cancel still follows world authority messages."},
    {"SendAddGroupMember", "GroupAddMemberRequest", "group", MigrationStatus::partial,
     "Add-member request is wired to the focused target and gateway online group registry."},
    {"SendDelGroupMember", "GroupRemoveMemberRequest", "group", MigrationStatus::partial,
     "Remove-member request is wired to the gateway online group registry with disband-on-singleton."},
    {"SendGuildHome", "GuildHomeRequest", "guild", MigrationStatus::partial,
     "Guild home request refreshes the gateway guild snapshot."},
    {"SendGuildMemberList", "GuildMemberListRequest", "guild", MigrationStatus::partial,
     "Guild member-list request refreshes the gateway guild snapshot."},
    {"SendGuildAddMem", "GuildAddMemberRequest", "guild", MigrationStatus::partial,
     "Guild add-member request updates the client_v1 gateway guild snapshot for visible online clients."},
    {"SendGuildDelMem", "GuildRemoveMemberRequest", "guild", MigrationStatus::partial,
     "Guild remove-member request updates the client_v1 gateway guild snapshot for visible online clients."},
    {"SendGuildUpdateNotice", "GuildUpdateNoticeRequest", "guild", MigrationStatus::partial,
     "Protocol and gateway notice refresh exist; the guild panel still lacks full Delphi editing UX."},
    {"SendGuildUpdateGrade", "GuildUpdateGradeRequest", "guild", MigrationStatus::partial,
     "Protocol and gateway rank-list refresh exist; the guild panel still lacks full Delphi editing UX."},
    {"SendSpeedHackUser", "SpeedHackReport", "security", MigrationStatus::planned,
     "Needs client-side detection cadence and server audit/rate-limit policy."},
    {"SendAdjustBonus", "AdjustBonusRequest", "character", MigrationStatus::planned,
     "Needs bonus allocation UI and authoritative character-stat update flow."},
    {"SendTimeTimerTimer", "Ping", "session", MigrationStatus::partial,
     "Ping/Pong exists, but the client has no scheduled heartbeat yet."},
}};

// ====================================================================
// 客户端接收消息映射表（39 条）
// 列出所有从服务端发送到客户端的消息及其新版映射
// ====================================================================
inline constexpr std::array<MappingEntry, 39> kDelphiClientGetMappings{{
    {"ClientGetPasswdSuccess", "LoginResult + ServerList", "login", MigrationStatus::partial,
     "Login success and server list exist; account-update/login-notice details are separate messages."},
    {"ClientGetNeedUpdateAccount", "NeedUpdateAccount + LoginScene update mode", "account",
     MigrationStatus::implemented, ""},
    {"ClientGetSelectServer", "ServerList + SelectServerResult + ServerSelectScene", "server_select",
     MigrationStatus::implemented, "Selection result carries character-gateway endpoint and lobby token."},
    {"ClientGetReceiveChrs", "CharacterList", "character", MigrationStatus::implemented, ""},
    {"ClientGetStartPlay", "SelectCharacterResult + LoginNotice + EnterWorldResult + WorldSnapshot",
     "world_entry", MigrationStatus::implemented,
     "World entry now waits on stLoginNotice/LoginNoticeOk before applying the snapshot."},
    {"ClientGetReconnect", "ReconnectResult", "connection", MigrationStatus::planned,
     "Needs a dedicated typed reconnect result once Delphi reconnect branches are ported."},
    {"ClientGetMapDescription", "MapDescription", "map", MigrationStatus::partial,
     "Map id and size exist; legacy description text and reconnect branches are still planned."},
    {"ClientGetAdjustBonus", "AdjustBonusState", "character", MigrationStatus::planned,
     "Needs bonus allocation state and UI before the legacy message can be represented."},
    {"ClientGetAddItem", "InventoryAdd", "inventory", MigrationStatus::partial,
     "Inventory add messages update the bag mirror and clear matching pending actions."},
    {"ClientGetUpdateItem", "InventoryUpdate", "inventory", MigrationStatus::partial,
     "Inventory update messages update the bag mirror and clear matching pending actions."},
    {"ClientGetDelItem", "InventoryRemove", "inventory", MigrationStatus::partial,
     "Inventory remove messages update the bag mirror and clear matching pending actions."},
    {"ClientGetDelItems", "InventoryClearRange", "inventory", MigrationStatus::partial,
     "Inventory clear-range messages update the bag mirror."},
    {"ClientGetBagItmes", "BagSnapshot", "inventory", MigrationStatus::partial,
     "Bag snapshots refresh the 46-slot bag mirror used by bag and belt UI."},
    {"ClientGetDropItemFail", "SysMessage", "inventory", MigrationStatus::partial,
     "Drop failures currently surface as system messages rather than a dedicated DropItemResult."},
    {"ClientGetShowItem", "GroundItemAdd", "world", MigrationStatus::partial,
     "Ground item lifecycle reaches WorldViewState; sprite-accurate item art is still planned."},
    {"ClientGetHideItem", "GroundItemRemove", "world", MigrationStatus::partial,
     "Ground item removal reaches WorldViewState."},
    {"ClientGetSenduseItems", "EquipmentSnapshot", "inventory", MigrationStatus::partial,
     "Equipment snapshots refresh the 13-slot equipment mirror; only classic visible slots have HUD hit areas."},
    {"ClientGetAddMagic", "MagicList refresh", "magic", MigrationStatus::partial,
     "Gateway folds add-magic updates into a refreshed MagicList."},
    {"ClientGetDelMagic", "MagicList refresh", "magic", MigrationStatus::partial,
     "Gateway folds delete-magic updates into a refreshed MagicList."},
    {"ClientGetMyMagics", "MagicList", "magic", MigrationStatus::partial,
     "MagicList drives the state-window magic page."},
    {"ClientGetMagicLvExp", "MagicList refresh", "magic", MigrationStatus::partial,
     "Gateway folds level/experience changes into a refreshed MagicList."},
    {"ClientGetDuraChange", "DurabilityChange", "inventory", MigrationStatus::partial,
     "Gateway translates SM_DURACHANGE to make-index durability updates for bag/equipment mirrors."},
    {"ClientGetMerchantSay", "NpcDialog", "npc", MigrationStatus::partial,
     "DMerchantDlg entry, text parser and link hit areas exist; shop lists and business panels are still planned."},
    {"ClientGetSendGoodsList", "MerchantGoodsList", "merchant", MigrationStatus::partial,
     "Merchant goods lists drive the buy window."},
    {"ClientGetSendMakeDrugList", "MakeDrugList", "merchant", MigrationStatus::planned,
     "Needs make-drug merchant panel state and gateway translation."},
    {"ClientGetSendUserSell", "MerchantPriceResult", "merchant", MigrationStatus::partial,
     "Sell selection and confirmation dialogs are represented by MerchantPriceResult state."},
    {"ClientGetSendUserRepair", "MerchantRepairPriceResult", "merchant", MigrationStatus::partial,
     "Repair selection and confirmation dialogs are represented by MerchantRepairPriceResult state."},
    {"ClientGetSendUserStorage", "StorageList", "storage", MigrationStatus::partial,
     "Storage open state is represented by StorageList."},
    {"ClientGetSaveItemList", "StorageList", "storage", MigrationStatus::partial,
     "Storage item lists drive the storage window."},
    {"ClientGetSendDetailGoodsList", "DetailGoodsList", "merchant", MigrationStatus::planned,
     "Needs detail-goods panel state and gateway translation."},
    {"ClientGetSendNotice", "Notice", "notice", MigrationStatus::implemented, ""},
    {"ClientGetGroupMembers", "GroupState", "group", MigrationStatus::partial,
     "Group state drives the group panel."},
    {"ClientGetOpenGuildDlg", "GuildState", "guild", MigrationStatus::partial,
     "Guild state drives the guild panel."},
    {"ClientGetSendGuildMemberList", "GuildState", "guild", MigrationStatus::partial,
     "Guild member lists are represented through GuildState."},
    {"ClientGetDealRemoteAddItem", "TradeState", "trade", MigrationStatus::partial,
     "Remote trade item changes are represented by refreshed TradeState."},
    {"ClientGetDealRemoteDelItem", "TradeState", "trade", MigrationStatus::partial,
     "Remote trade item removals are represented by refreshed TradeState."},
    {"ClientGetReadMiniMap", "MiniMapData", "map", MigrationStatus::partial,
     "MiniMapData drives the client mini-map panel."},
    {"ClientGetChangeGuildName", "GuildState", "guild", MigrationStatus::partial,
     "Guild name changes are represented through refreshed GuildState."},
    {"ClientGetSendUserState", "SelfAbilityDetail", "character", MigrationStatus::partial,
     "Detailed ability state drives the state window."},
}};

// ====================================================================
// 场景切换相关协议映射表
// 仅列出会直接驱动登录/选服/选角/创建角色/PlayScene 切换的消息。
// ====================================================================
inline constexpr std::array<MappingEntry, 13> kSceneTransitionMappings{{
    {"SendLogin", "LoginRequest", "login", MigrationStatus::implemented,
     "Login button sends this before any scene change; LoginResult/ServerList drive the next scene."},
    {"ClientGetPasswdSuccess", "LoginResult + ServerList -> ServerSelectScene", "login",
     MigrationStatus::partial,
     "client_v1 keeps LoginResult and ServerList typed but preserves receive order in the frame drain."},
    {"SendSelectServer", "SelectServerRequest", "server_select", MigrationStatus::implemented,
     "Server-select click sends the selected name and leaves the current UI pending until result."},
    {"ClientGetSelectServer", "SelectServerResult -> character gateway connect", "server_select",
     MigrationStatus::implemented,
     "Successful result carries lobby token and endpoint; CharacterListRequest follows connection."},
    {"SendQueryChr", "CharacterListRequest", "character", MigrationStatus::implemented,
     "Sent after selecting a server or refreshing create/delete results."},
    {"ClientGetReceiveChrs", "CharacterList -> CharacterSelectScene", "character",
     MigrationStatus::implemented,
     "Character slots are replaced from the typed list before switching to character select."},
    {"SendNewChr", "CreateCharacterRequest", "character_create", MigrationStatus::implemented,
     "Create dialog submits name/job/sex and waits for CreateCharacterResult."},
    {"ClientGetNewChr", "CreateCharacterResult -> CharacterListRequest", "character_create",
     MigrationStatus::implemented,
     "Success refreshes the character list; failure stays in create-character UI with modal text."},
    {"SendDelChr", "DeleteCharacterRequest", "character", MigrationStatus::implemented,
     "Delete confirmation sends the selected name and waits for DeleteCharacterResult."},
    {"ClientGetDelChr", "DeleteCharacterResult -> CharacterListRequest", "character",
     MigrationStatus::implemented,
     "Success refreshes the character list; failure keeps the current character-select scene."},
    {"SendSelChr", "SelectCharacterRequest", "character", MigrationStatus::implemented,
     "Selecting a character enters pending/loading only after the gateway accepts it."},
    {"ClientGetStartPlay", "SelectCharacterResult + LoginNotice + EnterWorldResult + WorldSnapshot",
     "world_entry", MigrationStatus::implemented,
     "Typed messages remain ordered; WorldSnapshot is the frame that applies world state and switches to PlayScene."},
    {"ClientGetServerDown", "DisconnectReason / DisconnectedEvent -> LoginScene", "connection",
     MigrationStatus::partial,
     "Server disconnect notices show modal text; complete Delphi reconnect edge cases remain planned."},
}};

}  // namespace mir2::client::protocol_migration
